### ISSUE TITLE
Uptime awards considered harmful?

### ISSUE THREAD

**Issue by alxndr42** [redpois0n/relayrewards#11]
Cool website, but: could encouraging people to leave their relay running continously for up to two years lead to security updates (that require reboots) not getting deployed?

**Comment by intchloe** [comment]
We haven't taken any consideration to that issue because it's possible to install important security updates without needing to reboot the server (even kernel updates, if you use something like [Ksplice](https://en.wikipedia.org/wiki/Ksplice)). 

Long-lasting relays are important for the Tor-network and should be treated likewise.

**Comment by wille** [comment]
Tor uptime is based on process uptime and not OS uptime from my experiences.

**Comment by alxndr42** [comment]
The majority of machines still needs to be rebooted for kernel updates. For OpenSSL fixes you have to at least restart the Tor process, which people might avoid to protect their precious uptime counter.

So I still think this award is promoting unsafe practices.
